### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by Huang-CL** [themaninthesuitcase/gimp-startrail-compositor#4]
I'm on a Ubuntu 16.04 laptop with a gimp 2.8.
I downloaded the python script and saved it at ~/.gimp-2.8/plug-ins/ or /usr/lib/gimp/2.0/plug-ins/.
I granted the execute permission to the script.  But the startrail option is not in the create menu after I restarted the gimp 2.8.
I tried with another desktop with Ubuntu 14.04 and gimp 2.8.  I encountered the same problem.

**Comment by themaninthesuitcase** [comment]
Just tested using ubuntu 17.4 (I dont have an install of an earlier version) and current GIMP 2.8.x.  I placed the startrail.py file into the default `~/.gimp-2.8/plug-ins/` folder and ran `chmod +x` on the file.  

After restarting GIMP the create menu contained the menu option as expected.  (File > Create > Startrail).

**Comment by Huang-CL** [comment]
@themaninthesuitcase Thank you for your comment. I believe I did the same thing as you mentioned.  Unfortunately, it didn't work for both my laptop and desktop. It's hard to believe that the different Ubuntu version causes the difference.

**Comment by PartialVolume** [comment]
@Huang-CL I know your issue was nearly a year ago, but this is one possible way to end up with the script not working .. Instead of downloading or cloning the Startrail project you simply click right on the startrail.py file on the main page and save the file to ~/.gimp-2.8/plug-ins/ it will save a file called startrail.py but it's contents won't be python it will be html and off course that won't work and when you restart gimp there won't be any startrail menu. So if the start of your startrail.py file looks anything like this ..

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">
```

then your not downloading the file correctly. The start of the starttrail.py file should look like this ..
```
https://github.com/themaninthesuitcase/gimp-startrail-compositor
Version : 1.8
Christopher Pearson
www.cpearson.me.uk
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
from gimpfu import *
from time import time
....
.... etc
```
